swagger: '2.0'
info:
  title: XSS Vulnerability API
  description: |
    This API is designed to simulate an XSS vulnerability.
    It reflects user input in the response without sanitization, allowing malicious scripts to execute.
  version: "1.0.0"
basePath: /api/v1
paths:
  /login:
    post:
      summary: Simulates a login attempt with XSS vulnerability
      description: |
        This endpoint takes a username and password, and reflects the username in the response without sanitizing it. This is a potential XSS vulnerability.
      parameters:
        - name: username
          in: formData
          description: The user's username
          required: true
          type: string
        - name: password
          in: formData
          description: The user's password
          required: true
          type: string
      responses:
        '200':
          description: Successful login (vulnerable to XSS)
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Welcome, <username>! You have successfully logged in."
        '400':
          description: Invalid input
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid credentials."
  /search:
    get:
      summary: Simulates a search endpoint with reflected XSS
      description: |
        This endpoint takes a search query and reflects the query in the response without sanitizing it, allowing XSS attacks.
      parameters:
        - name: query
          in: query
          description: The search query input
          required: true
          type: string
      responses:
        '200':
          description: Successful search (vulnerable to XSS)
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  type: string
                example:
                  - "<script>alert('XSS');</script> search result"
        '400':
          description: Invalid query
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Invalid search query."
